Feature - Add INS odom message and geonav_transform
Brazilian-Institute-of-Robotics/ixblue_ins_stdbin_driver pull request #4
Opened 2022-04-25 17:56 UTC by lucasmarbatista

- The driver publishes a `nav_msgs/Odometry` topic, integrating the DVL, IMU and INS data in only one message. 
- The "geonav_transform" converts the latitude and longitude position in meters. The node publish a `nav_msgs/Odometry`.
- The DVL message is corrected using the sound velocity measured by the SVS.

2022-04-25 19:45 UTC, migueelnery commented on ixblue_ins_driver/src/ros_publisher.cpp
> +  // Odom Covariance for pose(0, 7 and 14) and heading(21, 28 and 35)
I guess it should be "position (0, 7, and 14)", not "pose"

2022-04-26 16:22 UTC, carlospereira179 requested changes
Just minor changes sugested

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/launch/ixblue_ins_driver.launch
> +	<arg name="dvl_available" default="false"/>
this is launch here is called at ins_driver.launch from mccr_navigation. map this arg at the mccr_robot as an issue for further implementation

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/src/ins_to_odom.cpp
> +  // ins_dvl_listener_ = nh.subscribe("ixblue_ins_driver/ix/dvl", 1, &InsDvlListener::insDvlCallback, this);
this dvl subscription is commented because you yet have to test?

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/src/main.cpp
> +    InsDvlListener insDvlListenet();
typo `InsDvlListener insDvlListener();`

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/src/ins_to_odom.cpp
> +  ROS_WARN_STREAM("INS Latitude " << msg_ins->latitude << " graus");
`msg_ins->latitude << " graus");` change to `degrees` maybe?

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/src/ins_to_odom.cpp
> +}
EOF

2022-04-26 16:22 UTC, carlospereira179 commented on ixblue_ins_driver/src/ros_publisher.cpp
> +}
EOF

2022-04-28 11:23 UTC, carlospereira179 commented on ixblue_ins_driver/src/ros_publisher.cpp
> +}
Add this new line here too

2022-05-16 11:21 UTC, carlospereira179 approved these changes

2022-05-25 14:38 UTC, migueelnery approved these changes

2022-05-25 14:40 UTC, merged